name: Pterodactyl Eggs
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build dotnet egg for debian
        id: docker_build_debian
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dotnet-5.0.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eggs:dotnet-5.0
          
      - name: Build dotnet egg for alpine
        id: docker_build_alpine
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dotnet-5.0-alpine.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eggs:dotnet-5.0-alpine
